name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  charset_converter:
    git:
      url: https://github.com/nctpvtltdbutwal/charset_converter.git
      ref: master # branch name
      publish_to: none
  esc_pos_utils:
    git:
      url: https://github.com/nctpvtltdbutwal/esc_pos_utils.git
      ref: master # branch name
      publish_to: none
      
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  image: ^4.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
